### ISSUE TITLE
program close and finished after enter the selected serial number

### ISSUE THREAD

**Issue by huangkaiyan10** [sunwu51/JVMByteSwapTool#32]
![image](https://github.com/user-attachments/assets/3f96a2b4-75e6-4930-a6d6-23cbdd067d97)

**Comment by sunwu51** [comment]
It's just ok, the work of this process is attaching the host jvm. A server will start in the host jvm. Have a look at the log of  process with pid `2036`

**Comment by huangkaiyan10** [comment]
你的邮件我已经收到。谢谢
 
                              黄开雁

**Comment by huangkaiyan10** [comment]
but Visit this url http://localhost:8000 or http://localhost:8080 , is error.

**Comment by huangkaiyan10** [comment]
![image](https://github.com/user-attachments/assets/4e80e22d-f389-498b-b737-36675a7440fb)

**Comment by sunwu51** [comment]
Hi, I think there is a network problem in your browser. From the web console, you can see the js/css/png resources loaded time out.  So make sure your pc can connect the internet. For example, check you can access https://sunwu51.github.io/SwapperUI/.

In order to reduce the final jar size, and also for the decoupling for UI and backend, the frontend resources is located at `github.io`: [https://sunwu51.github.io/SwapperUI/](https://sunwu51.github.io/SwapperUI/). If you cannot visit github, maybe you can download the js/css and config it at the code, this is the source code location. https://github.com/sunwu51/JVMByteSwapTool/blob/master/src/main/resources/nanohttpd/index.html#L6-L7
